# Generated by Django 4.1.1 on 2022-09-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(max_length=50)),
                ("second_name", models.CharField(max_length=50)),
                ("years", models.DateField()),
                ("polis", models.CharField(max_length=16)),
                ("mobile_phone", models.CharField(max_length=11)),
                ("email_p", models.CharField(max_length=100)),
                ("registration_address", models.CharField(max_length=200)),
                ("fact_address", models.CharField(max_length=200)),
            ],
        ),
    ]
