# Generated by Django 4.1.1 on 2022-10-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("USER", "User"), ("ADMIN", "Admin"), ("DOCTOR", "Doctor")],
                default="USER",
                max_length=255,
            ),
        ),
    ]
