# Generated by Django 4.1.1 on 2022-09-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("years", models.DateTimeField()),
                ("policy", models.CharField(max_length=16)),
                ("mobile_phone", models.CharField(max_length=11)),
                ("email_p", models.EmailField(max_length=254)),
                ("registration_address", models.CharField(max_length=200)),
                ("fact_address", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=300)),
                ("zip_code", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="person",
            name="email_p",
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("event_date", models.DateTimeField()),
                ("manager", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("attendes", models.ManyToManyField(to="base.client")),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.venue",
                    ),
                ),
            ],
        ),
    ]
