# Generated by Django 4.1.1 on 2022-10-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="receptions",
            field=models.ManyToManyField(
                related_name="Receptions_booked_with_doctor", to="base.reception"
            ),
        ),
    ]
