# Generated by Django 4.1.1 on 2022-09-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_post_type_of_diagnoses_employees"),
    ]

    operations = [
        migrations.RemoveField(model_name="events", name="manager",),
        migrations.AddField(
            model_name="events",
            name="docror",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.employees",
            ),
        ),
        migrations.CreateModel(
            name="Visits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.events",
                    ),
                ),
            ],
        ),
    ]
