# Generated by Django 4.1.1 on 2022-10-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_doctor_type_availabletime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabletime",
            name="date",
            field=models.CharField(max_length=20),
        ),
    ]
