# Generated by Django 4.1.1 on 2022-10-23 12:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_availabletime_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tests",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_phone",
            field=models.CharField(
                default="",
                max_length=18,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Only numeric characters are allowed."
                    ),
                    django.core.validators.MaxLengthValidator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="polis",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_address",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="second_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="username", max_length=50),
        ),
        migrations.CreateModel(
            name="UserItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
